# Generated by Django 3.0 on 2019-12-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_link', models.TextField(help_text='The integration iframe link')),
                ('episode', models.IntegerField(help_text='The episode number')),
                ('serie', models.TextField(help_text="The serie's name")),
            ],
        ),
    ]
